### ISSUE TITLE
Roadmap of this package?

### ISSUE THREAD

**Issue by happyshows** [jimmybow/visdcc#10]
Hi,

I used below package in R and really like the features. Is the goal of this python library to get somewhere close to that package? With color-coding, grouping, shape, hover over tooltip, it could be much powerful package.

https://github.com/datastorm-open/visNetwork

**Comment by jimmybow** [comment]
there is no roadmap for this package currently.
that R  package visNetwork is similar to visdcc, they both use vis.js for plotting nerwork and can do the similar thing.

**Comment by jazon33y** [comment]
@jimmybow just my two cents; this package is really quite useful and so far it is one of the best user-implemented Dash component libraries out there. Well done, and thank you for your work.
