### ISSUE TITLE
How to change the layout of the generated Graph?

### ISSUE THREAD

**Issue by KaleabTessera** [jimmybow/visdcc#11]
Hi,

How would we go about changing the layout of the plotted graph? For example, if we wanted more space between the nodes.

**Comment by jimmybow** [comment]
hi, you can set the initial position (x, y) for your nodes
See documents of vis.js for setting of nodes  : https://visjs.github.io/vis-network/docs/network/nodes.html

**Comment by KaleabTessera** [comment]
Thanks!
