### ISSUE TITLE
Is it possible to render nodes as a text

### ISSUE THREAD

**Issue by reza1615** [jimmybow/visdcc#25]
My node's labels are long and having many ellipses is not interested. Is it possible to make the node border and backcolor as transparent?

![image](https://user-images.githubusercontent.com/2202483/102109726-5e6d2500-3e02-11eb-85b3-a48fe3f420f6.png)

**Comment by jimmybow** [comment]
yes,  you can change color, shape, etc.
see https://visjs.github.io/vis-network/docs/network/nodes.html for detail setting.

**Comment by reza1615** [comment]
Thank you This is very helpful. It would be nice to have it in the readme.
