### ISSUE TITLE
Is it possible to bring a node with connections to the front 

### ISSUE THREAD

**Issue by reza1615** [jimmybow/visdcc#26]
Is there any possibility to have something like [this](https://bl.ocks.org/almsuarez/4333a12d2531d6c1f6f22b74f2c57102)? when clicking on a node just that node and flowers are highlighted and the rest are fade.

**Comment by naston** [comment]
https://community.plotly.com/t/share-visdcc-a-dash-core-components-for-vis-js-network/5417/9
This should help.

**Comment by jimmybow** [comment]
you can also see [advanced usage example code](https://github.com/jimmybow/tree_vis)
