### ISSUE TITLE
Is it possible to trap "stabilizationIterationsDone" event?

### ISSUE THREAD

**Issue by LeMoussel** [jimmybow/visdcc#27]
I load the Network with physics and stabilization enabled. 
With visdcc, Is there any possibility once the nodes are stabilized to trap the stabilized event?
When the stabilized event is fired, I want to  disable the physics via network.setOptions.

For example, with `vis.js`, I do this:
```
network = new vis.Network(container, data, options);

network.on("stabilizationIterationsDone", function () {
    network.setOptions( { physics: false } );
});
```

**Comment by jimmybow** [comment]
i add a new feature on visdcc.Network
you can use this.net in javascript to get the instance of vis.Network
see the new v0.0.50 [example code](https://github.com/jimmybow/visdcc#animate-or-move-the-camera-by-javascript-)
