### ISSUE TITLE
hover information

### ISSUE THREAD

**Issue by dcoley13** [jimmybow/visdcc#4]
Hey jimmybow, thanks for porting vis.js to dash. I'm a big fan. I did have a quick question for you:
    I'm not not able to get the hover information when I hover over any of the nodes. Have you been able to get the tooltips when you use it? I've looked through their docs and believe I'm doing things correctly (even though I have very little experience with js in general). If that wasn't something you were interested in capturing when you ported then I might take a swing at it and let you know how it goes.

Thanks,

Doug

**Comment by aparna-k** [comment]
I need a way to get this to work too. Please let me know if you find a solution.

**Comment by aparna-k** [comment]
You have to add the VIS css explicitly:

```python
#external CSS stylesheets
external_stylesheets = [
    'https://cdnjs.cloudflare.com/ajax/libs/vis/4.20.1/vis.min.css',
]


app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
```
